name: Deploy to AWS S3
on:
  push:
    branches:
      - main

jobs:
  terraform-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v2

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v2
        with:
          terraform_version: 1.5.0

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v2
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-east-1

      - name: Initialize Terraform
        run: terraform init
        working-directory: ./terraform

      - name: Apply Terraform
        run: terraform apply -auto-approve
        working-directory: ./terraform

      - name: Output S3 Bucket Name (Step 1)
        id: output_bucket_name_step1
        run: |
          BUCKET_NAME=$(terraform output -raw s3_bucket_name)
        shell: bash

      - name: Set S3 Bucket Name as GitHub Environment Variable (Step 2)
        id: output_bucket_name_step2
        run: |
          echo "S3_BUCKET_NAME=$BUCKET_NAME" >> $GITHUB_ENV
        shell: bash



  deploy-web-app:
    runs-on: ubuntu-latest
    needs: terraform-deploy

    steps:
      - name: Checkout Code
        uses: actions/checkout@v2

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v2
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-east-1

      - name: Deploy Web App to S3
        run: aws s3 sync ./web s3://${{ env.S3_BUCKET_NAME }} --delete
